version: '3.8'

services:
  app:
    build: .
    container_name: aioc-app-container
    ports:
      - "8000:80" # Маппинг портов (Хост:Контейнер)
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway" # Чтобы контейнер видел Ollama на хосте
    restart: always